application: yoomph
version: 1
runtime: python
api_version: 1
# default_expiration: "7d"

handlers:
- url: /i
  static_dir: lib/images

- url: /js
  static_dir: lib/js

- url: /favicon.ico
  static_files: lib/images/favicon.ico
  upload: lib/images/favicon.ico

# - url: /
#   static_files: static/html/index.html
#   upload: static/html/index.html

- url: /.*
  script: lib/py/yoomph.py